import { describe, expect, it } from "vitest";
import { fetchDbConnection, fetchDbLink, parseDbLink, parseVbid, UnsafeJourneyLinkError, DbLinkImportError } from "./link";
import { parseDbTicketText } from "./pdf";
describe("DB import", () => {
  it("allows DB links and validates every redirect", async () => { expect(parseDbLink("https://reiseauskunft.bahn.de/bin/query.exe/en").hostname).toBe("reiseauskunft.bahn.de"); const fetcher = async () => new Response(null, { status: 302, headers: { location: "http://127.0.0.1/secret" } }); await expect(fetchDbLink("https://bahn.de/x", { fetcher })).rejects.toBeInstanceOf(UnsafeJourneyLinkError); });
  it("rejects non DB hosts", () => { expect(() => parseDbLink("https://bahn.de.evil.example/x")).toThrow(UnsafeJourneyLinkError); });
  it("validates vbids and ignores the large recon field", async () => { const url = "https://int.bahn.de/en/buchung/start?vbid=123e4567-e89b-12d3-a456-426614174000"; expect(parseVbid(url)).toBe("123e4567-e89b-12d3-a456-426614174000"); const fetcher = async (input: RequestInfo | URL, init?: RequestInit) => { expect(String(input)).toBe("https://int.bahn.de/web/api/angebote/verbindung/123e4567-e89b-12d3-a456-426614174000"); expect(init?.redirect).toBe("error"); return new Response(JSON.stringify({ startOrt: "Berlin Hbf", zielOrt: "Hamburg Hbf", hinfahrtDatum: "2026-08-27", hinfahrtRecon: "x".repeat(1501) }), { status: 200, headers: { "content-type": "application/json" } }); }; await expect(fetchDbConnection(url, { fetcher })).resolves.toMatchObject({ origin: "Berlin Hbf", destination: "Hamburg Hbf", departure: "2026-08-27T00:00:00.000Z" }); });
  it("rejects malformed vbids and API error responses", async () => { expect(() => parseVbid("https://int.bahn.de/en/buchung/start?vbid=not-a-uuid")).toThrow(DbLinkImportError); const fetcher = async () => new Response("", { status: 404, headers: { "content-type": "application/json" } }); await expect(fetchDbConnection("https://int.bahn.de/en/buchung/start?vbid=123e4567-e89b-12d3-a456-426614174000", { fetcher })).rejects.toMatchObject({ code: "not-found" }); });
  it("returns explicit ambiguity for incomplete ticket text", () => { const result = parseDbTicketText("My DB Reise\nBerlin Hbf\n27.08.2026"); expect(result.ambiguous.length).toBeGreaterThan(0); });
  it("extracts a clear German route", () => { const result = parseDbTicketText("Von Berlin Hbf Nach Hamburg Hbf\n27.08.2026\n10:00 11:45"); expect(result.origin?.name).toBe("Berlin Hbf"); expect(result.destination?.name).toBe("Hamburg Hbf"); expect(result.ambiguous).toEqual([]); });
});
